apiVersion: apps/v1
kind: Deployment
metadata:
  name: lawn-mowers-united
spec:
  selector:
    matchLabels:
      app: lawn-mowers-united
  replicas: 1
  template:
    metadata:
      labels:
        app: lawn-mowers-united
    spec:
      containers:
        - name: lawn-mowers-united
          image: leonardorocha1990/lawn-mowers-united:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 10
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k3s
            - name: PI_DB_HOST
              value: pi-mariadb
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password