apiVersion: v1
kind: Service
metadata:
  name: lawn-mowers-united
  labels:
    app: lawn-mowers-united
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30710
      protocol: TCP
      name: lawn-mowers-united
  selector:
    app: lawn-mowers-united